apiVersion: v1
kind: Pod
metadata:
  name: wes-camera-provisioner-test
spec:
  nodeSelector:
    node-role.kubernetes.io/master: "true"
  restartPolicy: Never
  serviceAccountName: wes-camera-provisioner-svc-account
  priorityClassName: wes-high-priority
  hostNetwork: true
  containers:
    - name: wes-camera-provisioner
      command: ["/bin/bash", "-c"]
      args: ["while true; do sleep 1; done"]
      image: waggle/wes-camera-provisioner:0.1.1
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
        limits:
          memory: 100Mi
      env:
        - name: WAGGLE_CAMERA_ADMIN
          valueFrom:
            secretKeyRef:
              name: wes-hanwha-camera-account-secret
              key: username
        - name: WAGGLE_CAMERA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wes-hanwha-camera-account-secret
              key: password
        - name: WAGGLE_CAMERA_USER
          valueFrom:
            secretKeyRef:
              name: wes-hanwha-camera-user-account-secret
              key: username
        - name: WAGGLE_CAMERA_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wes-hanwha-camera-user-account-secret
              key: password
        - name: WAGGLE_SWITCH_USER
          valueFrom:
            secretKeyRef:
              name: wes-networkswitch-account-secret
              key: username
        - name: WAGGLE_SWITCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wes-networkswitch-account-secret
              key: password
        - name: WAGGLE_MANIFEST_V2_PATH
          value: /etc/waggle/node-manifest-v2.json
      volumeMounts:
        - mountPath: /keys
          name: hanwha-client-ssh-key
          readOnly: true
        - mountPath: /etc/waggle
          name: waggle-node-manifest-v2
          readOnly: true
        - mountPath: /root/.ssh
          name: hanwha-client-ssh-config
          readOnly: true
        - mountPath: /data
          name: data
  volumes:
    - name: hanwha-client-ssh-key
      secret:
        secretName: wes-camera-provisioner-ssh-key
        defaultMode: 0600
    - name: waggle-node-manifest-v2
      configMap:
        name: waggle-node-manifest-v2
    - name: hanwha-client-ssh-config
      configMap:
        name: wes-camera-provisioner-ssh
    - name: data
      persistentVolumeClaim:
        claimName: wes-camera-provisioner-data
